title:            YUPRA
tagline:          'Summer REU 2024'
url:              https://jbirky.github.io
baseurl:          '/yupra'

author:
  name:           'Jessica Birky'

remote_theme: just-the-docs
